
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '701EEBF97B54A62907654A1284024ED9'
    
_lr_action_items = {'PLUS':([1,6,8,10,11,12,18,19,20,21,22,23,24,],[-12,-11,15,-12,15,15,15,-13,15,-8,-6,-7,-9,]),'DIVIDE':([1,6,8,10,11,12,18,19,20,21,22,23,24,],[-12,-11,17,-12,17,17,17,-13,17,-8,17,17,-9,]),'RPAREN':([6,10,12,19,20,21,22,23,24,],[-11,-12,19,-13,-10,-8,-6,-7,-9,]),'EXPONENT':([1,6,8,10,11,12,18,19,20,21,22,23,24,],[-12,-11,13,-12,13,13,13,-13,13,-8,-6,-7,-9,]),'VARNAME':([0,3,5,9,13,14,15,16,17,],[1,10,10,10,10,10,10,10,10,]),'LIST':([0,],[2,]),'EQUALS':([1,],[9,]),'TIMES':([1,6,8,10,11,12,18,19,20,21,22,23,24,],[-12,-11,14,-12,14,14,14,-13,14,-8,14,14,-9,]),'EXIT':([0,],[4,]),'LPAREN':([0,3,5,9,13,14,15,16,17,],[5,5,5,5,5,5,5,5,5,]),'PRINT':([0,],[3,]),'INTEGER':([0,3,5,9,13,14,15,16,17,],[6,6,6,6,6,6,6,6,6,]),'MINUS':([1,6,8,10,11,12,18,19,20,21,22,23,24,],[-12,-11,16,-12,16,16,16,-13,16,-8,-6,-7,-9,]),'$end':([1,2,4,6,7,8,10,11,18,19,20,21,22,23,24,],[-12,-5,-1,-11,0,-3,-12,-4,-2,-13,-10,-8,-6,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'nothing':([0,],[7,]),'expression':([0,3,5,9,13,14,15,16,17,],[8,11,12,18,20,21,22,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> nothing","S'",1,None,None,None),
  ('nothing -> EXIT','nothing',1,'p_exit','main.py',79),
  ('nothing -> VARNAME EQUALS expression','nothing',3,'p_assign','main.py',84),
  ('nothing -> expression','nothing',1,'p_calc','main.py',90),
  ('nothing -> PRINT expression','nothing',2,'p_print','main.py',95),
  ('nothing -> LIST','nothing',1,'p_list','main.py',100),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','main.py',105),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','main.py',110),
  ('expression -> expression TIMES expression','expression',3,'p_expression_times','main.py',115),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_divide','main.py',120),
  ('expression -> expression EXPONENT expression','expression',3,'p_expression_exponent','main.py',125),
  ('expression -> INTEGER','expression',1,'p_expression_integer','main.py',130),
  ('expression -> VARNAME','expression',1,'p_expression_varname','main.py',135),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_parens','main.py',140),
]
